language: php
sudo: false

php:
  - 5.6

install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  

before_script:
  - php app/console doctrine:schema:create -n
  - php app/console doctrine:schema:update --force --env test
  
  - php app/console doctrine:fixtures:load -n --env test
  - php app/console server:start

script:
  - php vendor/codeception/codeception/codecept run