language: php
sudo: false

php:
  - 5.6

install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer global require "fxp/composer-asset-plugin:~1.1.1"
  - composer install -n


before_script:
   
  - php bin/console doctrine:schema:update --force --env test
  
  - php bin/console doctrine:fixtures:load -n --env test
  - php bin/console server:start

script:
  - php vendor/codeception/codeception/codecept run acceptance
  - php vendor/codeception/codeception/codecept run -c src/AppBundle
  